version: "3.4"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./.docker/nginx/project.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
  backend:
    build: ./
    volumes:
      - ./center-managment-system:/app
    command: npm run start:dev:all
    depends_on:
      - rabbitmq
      - mysql
  frontend:
    build: ./
    volumes:
      - ./center-managment-ui:/app
    command: npm start
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysql-data:
